### PR TITLE
Add URL Filtering Capabilities to API Request Retrieval Functions

### LINKED ISSUE #298: Add a filter on api read
## Detailed Description
Add a filter that can only get or exclude strings when reading API users

## Context
- UI adds &UI to the end of all calls
- nice to be able to split between API and UI users

## Possible Implementation
- add include filter, e.g. include_in_url = 'UI' This should default to None. If not None,  `query = query.filter(APIRequestSQL.url.like(f'%{include_in_url}%')`
- add exclude filter e.g. exclude_in_url = 'UI. This should default to None. 
- add to two functions, this [one](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/read/read_user.py#L49) and this [one](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/read/read_user.py#L70)

### PR DESCRIPTION
**Pull request by Sahil-Chhoker**
## Description
Adds URL filtering capabilities to API request retrieval functions, enabling more granular control over request filtering.

### Changes
- Added `include_in_url` and `exclude_in_url` optional parameters to API request retrieval functions
- Implemented URL-based filtering using SQLAlchemy's `like()` method

## Fixes
Fixes #298 with ability to filter API requests by URL content.

## How Has This Been Tested?
- Manual testing of new filtering parameters
- Verified compatibility with existing codebase

### Test Configuration
- Python 3.8+
- SQLAlchemy 1.4.x
- Pytest for unit testing

## Checklist
- [x] Follows OCF coding style guidelines
- [x] Performed self-review of code
- [x] Updated inline documentation
- [ ] Added test cases (to be implemented)
- [x] Checked and corrected misspellings
- [x] Maintained existing function behavior

### CODE REVIEW

**Review by Sahil-Chhoker — COMMENTED** [review]
following ruff's checks

**Comment by Sahil-Chhoker** [comment]
Hi @peterdudfield, I am happy to add a teat case but I can't seen to fix the linting, also how can I make changes to code in this pr, or do I have to make a new one? Thanks for your time.

**Comment by peterdudfield** [comment]
> Hi @peterdudfield, I am happy to add a teat case but I can't seen to fix the linting, also how can I make changes to code in this pr, or do I have to make a new one? Thanks for your time.

Thanks @Sahil-Chhoker, adding a test case would be great. You should just push to you branch - 
[Sahil-Chhoker:feature/add-url-filtering-to-api-requests](https://github.com/Sahil-Chhoker/nowcasting_datamodel/tree/feature/add-url-filtering-to-api-requests)

No worries about linting, I can do that

**Comment by Sahil-Chhoker** [comment]
Hi @peterdudfield, I’ve updated the test file with new tests. Could you please review the changes and let me know if there’s anything that needs to be corrected? Thanks!

**Review by peterdudfield — APPROVED** [review]

**Pull request merged**
